spring.datasource.url=${DB_URL}
spring.datasource.username=${SB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration



server.port=8080
server.error.include-stacktrace=never

api.security.token.secret = ${JWT_SECRET:12345678}
api.security.token.expiration-hours = ${JWT_EXPIRATION_HOURS:2}

# Springdoc OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html